-- MySQL Script generated by MySQL Workbench
-- Sat Feb 17 11:24:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MestradoV01
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MestradoV01
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MestradoV01` DEFAULT CHARACTER SET utf8 ;
USE `MestradoV01` ;

-- -----------------------------------------------------
-- Table `MestradoV01`.`tb_areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MestradoV01`.`tb_areas` (
  `id_tb_areas` INT NOT NULL AUTO_INCREMENT,
  `tb_areas_nome` VARCHAR(45) NOT NULL,
  `tb_areas_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tb_areas`),
  UNIQUE INDEX `idArea_UNIQUE` (`id_tb_areas` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MestradoV01`.`tb_localizacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MestradoV01`.`tb_localizacoes` (
  `id_tb_localizacoes` INT NOT NULL AUTO_INCREMENT,
  `tb_localizacoes_local` VARCHAR(45) NULL,
  `tb_localizacoes_datum` VARCHAR(45) NULL,
  `tb_localizacoes_norte` FLOAT NULL,
  `tb_localizacoes_este` FLOAT NULL,
  `tb_localizacoes_elevacao` FLOAT NULL,
  `tb_localizacoes_comentario` VARCHAR(255) NULL,
  `tb_areas_id_tb_areas` INT NOT NULL,
  UNIQUE INDEX `idLocalizacao_UNIQUE` (`id_tb_localizacoes` ASC) VISIBLE,
  PRIMARY KEY (`id_tb_localizacoes`),
  INDEX `fk_tb_localizacoes_tb_areas_idx` (`tb_areas_id_tb_areas` ASC) VISIBLE,
  CONSTRAINT `fk_tb_localizacoes_tb_areas`
    FOREIGN KEY (`tb_areas_id_tb_areas`)
    REFERENCES `MestradoV01`.`tb_areas` (`id_tb_areas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MestradoV01`.`tb_projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MestradoV01`.`tb_projetos` (
  `id_tb_projetos` INT NOT NULL AUTO_INCREMENT,
  `tb_projetos_id_externo` VARCHAR(45) NULL,
  `tb_projetos_data_inicio` DATE NULL,
  `tb_projetos_data_final` DATE NULL,
  `tb_projetos_tipo` VARCHAR(45) NULL,
  `tb_projetos_status` VARCHAR(45) NULL,
  `tb_projetos_fase` VARCHAR(45) NULL,
  `tb_projetos_resp_tecnico` VARCHAR(45) NULL,
  `tb_projetos_cliente` VARCHAR(45) NULL,
  `tb_projetos_comentario` VARCHAR(255) NULL,
  `tb_areas_id_tb_areas` INT NOT NULL,
  PRIMARY KEY (`id_tb_projetos`),
  UNIQUE INDEX `idProjeto_UNIQUE` (`id_tb_projetos` ASC) VISIBLE,
  INDEX `fk_tb_projetos_tb_areas1_idx` (`tb_areas_id_tb_areas` ASC) VISIBLE,
  CONSTRAINT `fk_tb_projetos_tb_areas1`
    FOREIGN KEY (`tb_areas_id_tb_areas`)
    REFERENCES `MestradoV01`.`tb_areas` (`id_tb_areas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MestradoV01`.`tb_amostras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MestradoV01`.`tb_amostras` (
  `id_tb_amostras` INT NOT NULL AUTO_INCREMENT,
  `tb_amostras_codigo` VARCHAR(45) NULL,
  `tb_amostras_data_coleta` DATE NULL,
  `tb_amostras_material` VARCHAR(255) NULL,
  `tb_amostras_profundidade_topo` FLOAT NULL,
  `tb_amostras_profundidade_fundo` FLOAT NULL,
  `tb_amostras_status` VARCHAR(45) NULL,
  `tb_amostras_empresa_coleta` VARCHAR(45) NULL,
  `tb_amostras_revisor` VARCHAR(45) NULL,
  `tb_amostras_aprovador` VARCHAR(45) NULL,
  `tb_amostras_comentario` VARCHAR(255) NULL,
  `tb_localizacoes_id_tb_localizacoes` INT NOT NULL,
  `tb_projetos_id_tb_projetos` INT NOT NULL,
  PRIMARY KEY (`id_tb_amostras`),
  UNIQUE INDEX `idAmostra_UNIQUE` (`id_tb_amostras` ASC) VISIBLE,
  INDEX `fk_tb_amostras_tb_localizacoes1_idx` (`tb_localizacoes_id_tb_localizacoes` ASC) VISIBLE,
  INDEX `fk_tb_amostras_tb_projetos1_idx` (`tb_projetos_id_tb_projetos` ASC) VISIBLE,
  CONSTRAINT `fk_tb_amostras_tb_localizacoes1`
    FOREIGN KEY (`tb_localizacoes_id_tb_localizacoes`)
    REFERENCES `MestradoV01`.`tb_localizacoes` (`id_tb_localizacoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_amostras_tb_projetos1`
    FOREIGN KEY (`tb_projetos_id_tb_projetos`)
    REFERENCES `MestradoV01`.`tb_projetos` (`id_tb_projetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MestradoV01`.`tb_ensaios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MestradoV01`.`tb_ensaios` (
  `id_tb_ensaios` INT NOT NULL AUTO_INCREMENT,
  `tb_ensaios_cod_lab` VARCHAR(45) NULL,
  `tb_ensaios_tipo` VARCHAR(255) NOT NULL,
  `tb_ensaios_laboratorio` VARCHAR(45) NULL,
  `tb_ensaios_status` VARCHAR(45) NOT NULL,
  `tb_ensaios_data_inicio` DATE NULL,
  `tb_ensaios_data_final` DATE NULL,
  `tb_ensaios_revisor` VARCHAR(45) NULL,
  `tb_ensaios_aprovador` VARCHAR(45) NULL,
  `tb_ensaios_anexo` VARCHAR(255) NULL,
  `tb_ensaios_comentario` VARCHAR(255) NULL,
  `tb_amostras_id_tb_amostras` INT NOT NULL,
  PRIMARY KEY (`id_tb_ensaios`),
  UNIQUE INDEX `id_tb_ensaios_UNIQUE` (`id_tb_ensaios` ASC) VISIBLE,
  INDEX `fk_tb_ensaios_tb_amostras1_idx` (`tb_amostras_id_tb_amostras` ASC) VISIBLE,
  CONSTRAINT `fk_tb_ensaios_tb_amostras1`
    FOREIGN KEY (`tb_amostras_id_tb_amostras`)
    REFERENCES `MestradoV01`.`tb_amostras` (`id_tb_amostras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MestradoV01`.`tb_granulometrias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MestradoV01`.`tb_granulometrias` (
  `id_tb_granulometrias` INT NOT NULL AUTO_INCREMENT,
  `tb_granulometrias_diametro_particula` FLOAT NOT NULL,
  `tb_granulometrias_porcentagem_passante` FLOAT NOT NULL,
  `tb_granulometrias_comentario` VARCHAR(255) NULL,
  `tb_ensaios_id_tb_ensaios` INT NOT NULL,
  PRIMARY KEY (`id_tb_granulometrias`),
  UNIQUE INDEX `id_tb_granulometrias_UNIQUE` (`id_tb_granulometrias` ASC) VISIBLE,
  INDEX `fk_tb_granulometrias_tb_ensaios1_idx` (`tb_ensaios_id_tb_ensaios` ASC) VISIBLE,
  CONSTRAINT `fk_tb_granulometrias_tb_ensaios1`
    FOREIGN KEY (`tb_ensaios_id_tb_ensaios`)
    REFERENCES `MestradoV01`.`tb_ensaios` (`id_tb_ensaios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MestradoV01`.`tb_indices_consistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MestradoV01`.`tb_indices_consistencia` (
  `id_tb_indices_consistencia` INT NOT NULL AUTO_INCREMENT,
  `tb_indices_consistencia_limite_liquidez` FLOAT NOT NULL,
  `tb_indices_consistencia_limite_plasticidade` FLOAT NOT NULL COMMENT 'Para os indices de consistência os valores não plastico e não liquido serão representados como \"999\"',
  `tb_indices_consistencia_comentario` VARCHAR(255) NULL,
  `tb_ensaios_id_tb_ensaios` INT NOT NULL,
  PRIMARY KEY (`id_tb_indices_consistencia`),
  UNIQUE INDEX `id_tb_indices_consistencia_UNIQUE` (`id_tb_indices_consistencia` ASC) VISIBLE,
  INDEX `fk_tb_indices_consistencia_tb_ensaios1_idx` (`tb_ensaios_id_tb_ensaios` ASC) VISIBLE,
  CONSTRAINT `fk_tb_indices_consistencia_tb_ensaios1`
    FOREIGN KEY (`tb_ensaios_id_tb_ensaios`)
    REFERENCES `MestradoV01`.`tb_ensaios` (`id_tb_ensaios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MestradoV01`.`tb_pesos_especificos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MestradoV01`.`tb_pesos_especificos` (
  `id_tb_pesos_especificos` INT NOT NULL AUTO_INCREMENT,
  `tb_pesos_especificos_peso_natural` DECIMAL(20) NULL,
  `tb_pesos_especificos_peso_aparente_seco` DECIMAL(20) NULL,
  `tb_pesos_especificos_peso_especifico_graos` FLOAT NULL,
  `tb_pesos_especificos_peso_natural_teor_umidade` FLOAT NULL,
  `tb_pesos_especificos_comentario` VARCHAR(255) NULL,
  `tb_ensaios_id_tb_ensaios` INT NOT NULL,
  PRIMARY KEY (`id_tb_pesos_especificos`),
  UNIQUE INDEX `id_tb_pesos_especificos_UNIQUE` (`id_tb_pesos_especificos` ASC) VISIBLE,
  INDEX `fk_tb_pesos_especificos_tb_ensaios1_idx` (`tb_ensaios_id_tb_ensaios` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pesos_especificos_tb_ensaios1`
    FOREIGN KEY (`tb_ensaios_id_tb_ensaios`)
    REFERENCES `MestradoV01`.`tb_ensaios` (`id_tb_ensaios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MestradoV01`.`tb_umidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MestradoV01`.`tb_umidades` (
  `id_tb_umidades` INT NOT NULL AUTO_INCREMENT,
  `tb_umidades_teor_umidade` FLOAT NOT NULL,
  `tb_umidades_metodo_ensaio` VARCHAR(255) NULL,
  `tb_umidades_norma_referencia` VARCHAR(255) NULL,
  `tb_umidades_comentario` VARCHAR(255) NULL,
  `tb_ensaios_id_tb_ensaios` INT NOT NULL,
  PRIMARY KEY (`id_tb_umidades`),
  UNIQUE INDEX `id_tb_umidades_UNIQUE` (`id_tb_umidades` ASC) VISIBLE,
  INDEX `fk_tb_umidades_tb_ensaios1_idx` (`tb_ensaios_id_tb_ensaios` ASC) VISIBLE,
  CONSTRAINT `fk_tb_umidades_tb_ensaios1`
    FOREIGN KEY (`tb_ensaios_id_tb_ensaios`)
    REFERENCES `MestradoV01`.`tb_ensaios` (`id_tb_ensaios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MestradoV01`.`tb_investigacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MestradoV01`.`tb_investigacoes` (
  `id_tb_investigacoes` INT NOT NULL AUTO_INCREMENT,
  `tb_investigacoes_status` VARCHAR(45) NOT NULL,
  `tb_investigacoes_data_inicio` DATE NULL,
  `tb_investigacoes_data_final` DATE NULL,
  `tb_investigacoes_codigo_investigacao` VARCHAR(45) NULL,
  `tb_investigacoes_tipo` VARCHAR(45) NOT NULL,
  `tb_investigacoes_empresa_responsavel` VARCHAR(45) NULL,
  `tb_investigacoes_revisor` VARCHAR(45) NULL,
  `tb_investigacoes_aprovador` VARCHAR(45) NULL,
  `tb_localizacoes_id_tb_localizacoes` INT NOT NULL,
  `tb_projetos_id_tb_projetos` INT NOT NULL,
  PRIMARY KEY (`id_tb_investigacoes`),
  UNIQUE INDEX `id_tb_investigacoes_UNIQUE` (`id_tb_investigacoes` ASC) VISIBLE,
  INDEX `fk_tb_investigacoes_tb_localizacoes1_idx` (`tb_localizacoes_id_tb_localizacoes` ASC) VISIBLE,
  INDEX `fk_tb_investigacoes_tb_projetos1_idx` (`tb_projetos_id_tb_projetos` ASC) VISIBLE,
  CONSTRAINT `fk_tb_investigacoes_tb_localizacoes1`
    FOREIGN KEY (`tb_localizacoes_id_tb_localizacoes`)
    REFERENCES `MestradoV01`.`tb_localizacoes` (`id_tb_localizacoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_investigacoes_tb_projetos1`
    FOREIGN KEY (`tb_projetos_id_tb_projetos`)
    REFERENCES `MestradoV01`.`tb_projetos` (`id_tb_projetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MestradoV01`.`tb_spt_informacoes_gerais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MestradoV01`.`tb_spt_informacoes_gerais` (
  `idtb_spt_informacoes_gerais` INT NOT NULL AUTO_INCREMENT,
  `tb_spt_informacoes_gerais_profundidade_total` DECIMAL(20) NOT NULL,
  `tb_spt_informacoes_gerais_nivel_agua` FLOAT NULL,
  `tb_spt_informacoes_gerais_tipo_acionamento` VARCHAR(45) NULL,
  `tb_spt_informacoes_gerais_condicao_equipamento` VARCHAR(45) NULL,
  `tb_spt_informacoes_gerais_tipo_equipamento` VARCHAR(45) NULL,
  `tb_spt_informacoes_gerais_percentual_energia` FLOAT NULL,
  `tb_spt_informacoes_gerais_anexo` VARCHAR(255) NULL,
  `tb_spt_informacoes_gerais_comentario` VARCHAR(255) NULL,
  `tb_investigacoes_id_tb_investigacoes` INT NOT NULL,
  PRIMARY KEY (`idtb_spt_informacoes_gerais`),
  UNIQUE INDEX `idtb_spt_informacoes_gerais_UNIQUE` (`idtb_spt_informacoes_gerais` ASC) VISIBLE,
  INDEX `fk_tb_spt_informacoes_gerais_tb_investigacoes1_idx` (`tb_investigacoes_id_tb_investigacoes` ASC) VISIBLE,
  CONSTRAINT `fk_tb_spt_informacoes_gerais_tb_investigacoes1`
    FOREIGN KEY (`tb_investigacoes_id_tb_investigacoes`)
    REFERENCES `MestradoV01`.`tb_investigacoes` (`id_tb_investigacoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MestradoV01`.`tb_spt_dados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MestradoV01`.`tb_spt_dados` (
  `id_tb_spt_dados` INT NOT NULL AUTO_INCREMENT,
  `tb_spt_dados_profundidade` FLOAT NOT NULL,
  `tb_spt_dados_golpes_1` INT NULL,
  `tb_spt_dados_avanco_1` INT NULL,
  `tb_spt_dados_golpes_2` INT NULL,
  `tb_spt_dados_avanco_2` INT NULL,
  `tb_spt_dados_golpes_3` INT NULL,
  `tb_spt_dados_avanco_3` INT NULL,
  `tb_spt_dados_descricao_geologica` VARCHAR(255) NOT NULL,
  `tb_spt_dados_fracao_1` VARCHAR(45) NOT NULL,
  `tb_spt_dados_fracao_2` VARCHAR(45) NULL,
  `tb_spt_dados_fracao_3` VARCHAR(45) NULL,
  `tb_spt_informacoes_gerais_idtb_spt_informacoes_gerais` INT NOT NULL,
  PRIMARY KEY (`id_tb_spt_dados`),
  UNIQUE INDEX `id_tb_spt_dados_UNIQUE` (`id_tb_spt_dados` ASC) VISIBLE,
  INDEX `fk_tb_spt_dados_tb_spt_informacoes_gerais1_idx` (`tb_spt_informacoes_gerais_idtb_spt_informacoes_gerais` ASC) VISIBLE,
  CONSTRAINT `fk_tb_spt_dados_tb_spt_informacoes_gerais1`
    FOREIGN KEY (`tb_spt_informacoes_gerais_idtb_spt_informacoes_gerais`)
    REFERENCES `MestradoV01`.`tb_spt_informacoes_gerais` (`idtb_spt_informacoes_gerais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
